name: Publish to PyPI

description: |
  Download the built distributions and publish them to PyPI.
  `⚠️ DEPRECATED` This action is no longer maintained. Please use publish-to-pipy-with-uv.

runs:
  using: "composite"
  steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.0
