name: 🔥 Create Git Tag 🎉
description: Creates a Git tag based on the version and adds commit details and PR info.

inputs:
  tag_name:
    description: The tag name to create.
    required: true
  commits:
    description: The commit messages to include in the tag description.
    required: true
  title:
    description: The PR title to include in the tag description.
    required: true
  description:
    description: The PR body description to include in the tag description.
    required: false
  emoji:
    description: Emojis to add to the tag message.
    required: false
    default: "✨🚀"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Git Tag
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        
        tag_message="${{ inputs.emoji }} ${{ inputs.title }}: ${{ inputs.description }}"
        commits_text="Merged Commits:\n${{ inputs.commits }}"

        git tag -a ${{ inputs.tag_name }} -m "$tag_message [skip ci]" -m "$commits_text"
        git push origin ${{ inputs.tag_name }}
      shell: bash
