name: Publish to PyPI using uv

description: |
  Download the built distributions and publish them to PyPI.

inputs:
  python_version:
    description: 'The Python version to use'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution to PyPI
      run: uv publish
      shell: bash