name: Build Distribution

description: Build a binary wheel and a source tarball for Python packages.

inputs:
  python_version:
    description: 'The Python version to use'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Build a binary wheel and a source tarball
      run: uv build
      shell: bash

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
